# Helper functions for calculating differences in demand as calculated either by
# ambrosia or by GCAM

# Function to subtract all elements of two income/price scenarios of 
# food demand and elasticities (scen1 - scen2). Assumes original scenario results
# exist as separate files for each region, for example as produced by ambrosia
# ensemble runs. Carried out for regions defined in "regions", keeping columns
# that should not be subtracted.
subtract_demand_dfs <- function(scen1, case1, path1, 
                                scen2, case2, path2,
                                out_dir, regions) {
  
  # Columns that define corresponding rows
  by_cols <- c("GCAM_region_ID", "region", "year", "gcam-consumer", "iteration")
  
  for (r in seq_along(regions)) {
    
    # Load regional demand for two scenarios to subtract
    df1 <- readRDS(file.path(path1, paste0("demand_R", regions[r], case1, ".RDS")))
    df2 <- readRDS(file.path(path2, paste0("demand_R", regions[r], case2, ".RDS")))
    
    # Safely drop rgn if present
    df1_clean <- df1 %>% select(-any_of("rgn"))
    df2_clean <- df2 %>% select(-any_of("rgn"))
    
    # Identify common numeric columns to subtract, excluding keys and LL
    common <- intersect(names(df1_clean), names(df2_clean))
    numeric_common <- setdiff(common, c(by_cols, "LL"))
    numeric_common <- numeric_common[
      sapply(numeric_common, function(v)
        is.numeric(df1_clean[[v]]) && is.numeric(df2_clean[[v]])
      )
    ]
    
    # Columns that will be kept in the diff output
    kept_cols <- c(by_cols, "LL", numeric_common)
    all_input_cols <- union(names(df1_clean), names(df2_clean))
    dropped_cols <- setdiff(all_input_cols, kept_cols)
    
    if (length(dropped_cols) > 0) {
      message("Region ", regions[r],
              ": dropping columns from diff: ",
              paste(dropped_cols, collapse = ", "))
    }
    
    # Join the two data frames on key columns
    joined <- inner_join(
      df1_clean,
      df2_clean,
      by = by_cols,
      suffix = c(".df1", ".df2")
    )
    
    # Build list of difference columns (df1 - df2) in base R
    diff_list <- setNames(
      lapply(numeric_common, function(col) {
        joined[[paste0(col, ".df1")]] - joined[[paste0(col, ".df2")]]
      }),
      numeric_common
    )
    
    # Assemble final diffs_reg: keys + LL from df1 + numeric differences
    diffs_reg <- cbind(
      joined[, by_cols, drop = FALSE],
      LL = joined[["LL.df1"]],
      as.data.frame(diff_list, check.names = FALSE)
    )
    
    # Save in scen1 directory
    saveRDS(
      diffs_reg,
      file.path(out_dir, 
                paste0("demand_R", regions[r], "_diffs", case2, ".RDS"))
    )
  }
}

# Function to subtract all elements of two income/price scenarios of 
# food demand and elasticities (scen1 - scen2) as generated by GCAM. Assumes original 
# scenario results exist as a single file for each scenario containing all regions.
# Keeps columns that should not be subtracted.
subtract_gcam_demand_dfs <- function(df_scen_var, case_var, df_scen_base, case_base,
                                     out_dir) {
  
  # Columns that define corresponding rows
  by_cols <- c("GCAM_region_ID", "region", "year", "gcam-consumer")
  
  # Identify common numeric columns to subtract, excluding keys and LL
  common <- intersect(names(df_scen_var), names(df_scen_base))
  numeric_common <- setdiff(common, by_cols)
  numeric_common <- numeric_common[
    sapply(numeric_common, function(v)
      is.numeric(df_scen_var[[v]]) && is.numeric(df_scen_base[[v]])
    )
  ]
  
  # Columns that will be kept in the diff output
  kept_cols <- c(by_cols, numeric_common)
  all_input_cols <- union(names(df_scen_var), names(df_scen_base))
  dropped_cols <- setdiff(all_input_cols, kept_cols)
  
  if (length(dropped_cols) > 0) {
    message("Dropping columns from diff: ",
            paste(dropped_cols, collapse = ", "))
  }
  
  # Join the two data frames on key columns
  joined <- inner_join(
    df_scen_var,
    df_scen_base,
    by = by_cols,
    suffix = c(".dfvar", ".dfbase")
  )
  
  # Build list of difference columns (dfvar - dfbase) in base R
  diff_list <- setNames(
    lapply(numeric_common, function(col) {
      joined[[paste0(col, ".dfvar")]] - joined[[paste0(col, ".dfbase")]]
    }),
    numeric_common
  )
  
  # Assemble final diffs: keys + numeric differences
  diffs <- cbind(
    joined[, by_cols, drop = FALSE],
    as.data.frame(diff_list, check.names = FALSE)
  )
  
  # Save in output directory
  saveRDS(
    diffs,
    file.path(out_dir, paste0("gcamoutput_diffs_", case_base, "_", case_var, ".RDS"))
  )
}
